"""Role-prompt definitions layered on top of ResearchHarness."""

from markscientist.prompts.role_prompts import (
    CHALLENGE_REQUEST_TEMPLATE,
    CHALLENGER_IMPROVEMENT_GUIDANCE_TEMPLATE,
    CHALLENGER_ROLE_PROMPT,
    JUDGE_REQUEST_TEMPLATE,
    JUDGE_ROLE_PROMPT,
    SOLVER_ROLE_PROMPT,
    SOLVER_FINALIZATION_GUIDANCE_TEMPLATE,
    SOLVER_IMPROVEMENT_GUIDANCE_TEMPLATE,
    SOLVER_REQUEST_TEMPLATE,
)

__all__ = [
    "CHALLENGER_ROLE_PROMPT",
    "SOLVER_ROLE_PROMPT",
    "JUDGE_ROLE_PROMPT",
    "CHALLENGE_REQUEST_TEMPLATE",
    "CHALLENGER_IMPROVEMENT_GUIDANCE_TEMPLATE",
    "SOLVER_REQUEST_TEMPLATE",
    "SOLVER_FINALIZATION_GUIDANCE_TEMPLATE",
    "SOLVER_IMPROVEMENT_GUIDANCE_TEMPLATE",
    "JUDGE_REQUEST_TEMPLATE",
]
